config/routes.rb
Rails.application.routes.draw do

  resources :searches, only: [:index, :new, :create], :path => "search"
  resources :claims, only: [:show]
  devise_for :users

  root 'searches#new'

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :sectors
end

app/models/claim.rb
class Claim < ActiveRecord::Base
  belongs_to :policy
  belongs_to :vehicle
  belongs_to :claim_type
  belongs_to :claim_status
  
  has_paper_trail
end

app/models/claim_status.rb
class ClaimStatus < ActiveRecord::Base
  has_many :claims
end

app/models/claim_type.rb
class ClaimType < ActiveRecord::Base
  has_many :claims
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :sector
  has_many :policies
  
  has_paper_trail
  
  before_validation do
    self.name = name.strip.downcase.split.map(&:capitalize).join(" ") if name.present?
    self.surname = surname.strip.downcase.split.map(&:capitalize).join(" ") if surname.present?
    self.identification = identification.strip.gsub(/[^0-9]/, '') if identification.present?
  end

  
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }, format: { with: /\p{L}/ }
  validates :surname, presence: true, length: { minimum: 2, maximum: 50 }, format: { with: /\p{L}/ }
  
  validates :identification, presence: true, uniqueness: true, numericality: { only_integer: true }, length: { is: 11 }
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :sector
  has_many :policies
  
  has_paper_trail
  
  validates :name, presence: true, length: { minimum: 2, maximum: 60 }
  
  validates :rnc, presence: true, uniqueness: true, numericality: { only_integer: true }, length: { is: 9 }

  

end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	has_many :policies
	has_many :users
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  belongs_to :insurance
  belongs_to :client
  belongs_to :company
  has_many :claims
  has_and_belongs_to_many :vehicles

  has_paper_trail
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  belongs_to :city
  has_many :clients
  has_many :companies
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable, :lockable,
         :recoverable, :trackable, :validatable, :registerable
         
	belongs_to :insurance
	
	has_paper_trail
	
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :vehicle_model
  has_many :claims
  has_and_belongs_to_many :policies
  
  has_paper_trail
  
  before_validation do
    self.plate = plate.upcase
  end
  
  #validates :vin, presence: true, uniqueness: true
  #validates :plate, presence: true, uniqueness: true
  
end

app/models/vehicle_brand.rb
class VehicleBrand < ActiveRecord::Base
	has_many :vehicle_models
end

app/models/vehicle_model.rb
class VehicleModel < ActiveRecord::Base
  belongs_to :vehicle_brand
  has_many :vehicles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :create, only: [:index]
  before_action :set_target, only: [:index]



  # Results 
  def index
    if @client
      @policies = @client.policies
      @client_history = Search.joins(:user).where("searches.client = ?", @client.identification).group("users.insurance_id, searches.date, searches.id")
      lookup_tickets(@client.identification)
    elsif @company
      @policies = @company.policies
    elsif @vehicle
    
    else
      render action: 'not_found'
    end   
    
  end

  # New Search Root
  def new
  end
  
  # Save User Search
  def create    
    @search = Search.new(search_params)
    @search.user_id = current_user.id
    @search.date = Date.today
		@search.save
  end
  
  def not_found
    
  end


  private
  
		# Set Client and Vehicle variables
		def set_target
		  
			client_query = params[:client]
			vehicle_query = params[:vehicle]
			
			unless client_query.blank?
			
			  client_query = client_query.strip.gsub(/[^0-9]/, '') 
			
				if client_query.length == 11
					@client = Client.find_by(identification: client_query)
				elsif client_query.length == 9 
					@company = Company.find_by(rnc: client_query)
				end
			else
				#load with dummy data to show off results view
				client_query = '00117999383'
				@client = Client.find_by(identification: client_query)
			end
			
			
			unless vehicle_query.blank?
			
				if vehicle_query.length == 17      
					@vehicle = Vehicle.find_by(vin: vehicle_query)
				elsif vehicle_query.length < 8
				  vehicle_query.upcase!
					@vehicle = Vehicle.find_by(plate: vehicle_query) 
				end  
			else
				#load with dummy data to show off results view
				vehicle_query = '1HGBH41JXMN109186'
				@vehicle = Vehicle.find_by(vin: vehicle_query)
			end
			
		end
		
		#Look for tickets in AMET
		def lookup_tickets(cedula)
			agent = Mechanize.new
			page = agent.get('http://consultas.amet.gob.do/')
			form = agent.page.forms.first  
			field = form.field_with(:id => "ctl00_ContentPlaceHolder1_Cedula")
			field.value = cedula  
			form.submit form.button_with(:name => "ctl00$ContentPlaceHolder1$BotonValidar")
			tickets = agent.page.at('#ctl00_ContentPlaceHolder1_GridViewMultas')
			#parse_tickets(tickets)
			@tickets = tickets
	
		end

		#Parse Tickets (no longer needed after AMET redesigned website)
		def parse_tickets(tickets)
			tickets.search("//b").each do |node|
				node.replace Nokogiri::XML::Text.new(node.inner_html, node.document)
			end
		
			tickets.search("//font").each do |node|
				node.replace Nokogiri::XML::Text.new(node.inner_html, node.document)
			end
		
			tickets.search('//*[@align="right"]').each do |node|
				node.remove
			end
			
			tickets.at('//*[@colspan="5"]').remove
		
			@tickets = tickets
		end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.permit(:client, :vehicle)
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper

	def get_gender(boolean)
    if boolean == true
      "Masculino"
    else
      "Femenino"
    end
  end
  
  
  def get_coverage(boolean)
    if boolean == true
      "DP"
    else
      "Ley"
    end
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper

  def nav_link(link_text, link_path, link_id = "")
    class_name = current_page?(link_path) ? 'current' : nil
    content_tag(:li, :class => class_name, id: link_id) do
      link_to link_text, link_path
    end
  end
  
  
  def get_client_details(policy)
  
  	if policy.client_id 	
  	  details = [[policy.client.name,policy.client.surname].join(' '), policy.client.identification.insert(3, '-').insert(11, '-')]  
  	elsif policy.company_id
  	  details = [policy.company.name, policy.company.rnc.to_s.insert(3, '-').insert(7, '-')]  
  	end
  	content_tag :ul do
  	    details.collect {|item| concat(content_tag(:li, item))}
  	  end
  end
  
  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  
end

app/views/layouts/_footer.html.haml
%footer
  .datalist
  .datalist
  .datalist

app/views/layouts/_header.html.haml
%header
  = link_to '', root_path, :id => 'logo'
  - if user_signed_in?  
    #log_out= link_to "[", destroy_user_session_path, :method => :delete
    #settings 
      @
      %ul#pop_menu
        = nav_link 'Mi Perfil', '#'
        = nav_link 'Términos y Condiciones', '#'
        = nav_link 'Políticas de Privacidad', '#'
    #username
      #user_icon +
      = current_user.name
      
      

#print_header
  .left
    #print_logo= image_tag("logo.png")
    %p Teléfono: 809.555.0343
    %p RNC: 101-00011-2
  .right
    %p Pág 1 de 1
    %br
    %p= Date.today.strftime("%d/%b/%Y")
    %p= Time.now.strftime("%I:%M %p")
  .print_title Reporte de Siniestros
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}
    %title Datasin
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body{:signed_in => "#{user_signed_in?}"}
    #all{:action => "#{params[:controller] + "_" + params[:action]}"}
      = render "layouts/header" if user_signed_in?
      #content
        - if flash[:notice] 
          #notice
            %span= flash[:notice]
        - if flash[:alert] 
          #alert
            %span= flash[:alert] 
        = yield
        
      

app/views/searches/_sidebar.html.haml
#sidebar
  %ul#side_menu
    - if @client
      = nav_link 'Cliente', '#', 'client_icon'
      %ul
        %li= [@client.name, @client.surname].join(" ")
        %ul
          %li
            .bubble= @policies.count.to_s
            %span  Pólizas
          - unless @policies.empty? 
            - @policies.order("start desc").each do |p|
              %ul
                %li= p.policy
                - unless p.claims.empty?
                  %ul   
                    - p.claims.order("created_at desc").each do |c|
                      %li= c.number
                  
    - if @company
      = nav_link 'Cliente', "#", 'client_icon'
      %ul
        %li= @company.name
        %ul
          %li
            .bubble= @policies.count.to_s
            %span  Pólizas
          - unless @policies.empty? 
            - @policies.order("start desc").each do |p|
              %ul
                %li= p.policy
                - unless p.claims.empty?
                  %ul   
                    - p.claims.order("created_at desc").each do |c|
                      %li= c.number
                     
    - if @vehicle
      = nav_link 'Vehículo', '#', 'vehicle_icon'
      %ul
        %li= [@vehicle.vehicle_model.vehicle_brand.name, @vehicle.vehicle_model.name, @vehicle.year.to_s].join(' ')
        %ul
          %li
            .bubble= @vehicle.policies.count.to_s
            %span  Pólizas
          - unless @vehicle.policies.empty? 
            - @vehicle.policies.order("start desc").each do |p|
              %ul
                %li= p.policy
                - unless p.claims.empty?
                  %ul   
                    - p.claims.order("created_at desc").each do |c|
                      %li= c.number
    

app/views/searches/index.html.haml
#Loader
%script{:type => "text/javascript"}
  $("#Loader").fakeLoader({timeToHide:4000, zIndex:"19", spinner:"spinner2", bgColor:"#2C3E50"});

= render 'searches/sidebar'        
        
#results

  #client_report.page{:unactive => "#{@client.nil?}"}
    - if @client
    
      .main_block
        .info
          %h2= [@client.name, @client.surname].join(' ')
          - if @client.identification
            %h4.identification <span>Cédula</span> #{@client.identification.insert(3, '-').insert(11, '-')}
          - if @client.gender
            %h4.sex <span>Sexo</span> #{get_gender @client.gender}
          - if @client.birthdate
            %h4.birthdate <span>Edad</span> #{age @client.birthdate}
          - if @client.occupation
            %h4.job <span>Ocupación</span> #{@client.occupation}
          - if @client.sector
            %h4.sector <span>Sector</span> #{@client.sector.name}
        = link_to 'Imprimir', '#', :class => "print"
     
        
      .breaker= @policies.count.to_s + " Pólizas"   
      - unless @policies.empty? 
        - @policies.order("start desc").each do |p|
          .block
            .block_header
              .policy_number= 'Póliza # ' + p.policy
              .insurance_name= p.insurance.company
              .coverage_type= get_coverage p.coverage
              .claims_count
                .bubble= p.claims.count.to_s 
                %span  reclamaciones
              .end_date= p.end.strftime("%d/%b/%Y")            
              .start_date= p.start.strftime("%d/%b/%Y")
            %table{:cellpading => '0', :cellspacing => 0}
              - unless p.claims.empty? 
                %tr
                  %th No. Reclamación
                  %th Vehículo
                  %th Placa
                  %th Chasis
                  %th Fecha
                  %th Tipo
                  %th Estado  
                - p.claims.order("created_at desc").each do |c|
                  %tr{:class => cycle('odd', 'even')}
                    %td= c.number
                    %td= [c.vehicle.vehicle_model.vehicle_brand.name,c.vehicle.vehicle_model.name,c.vehicle.year.to_s].join(' ')
                    %td= c.vehicle.plate
                    %td= c.vehicle.vin
                    %td= c.date.strftime("%d/%b/%Y")
                    %td= c.claim_type.name
                    %td= c.claim_status.status
              - else
                %td.none_found No se encontraron reclamaciones.
		
      - if @tickets
        #multas.breaker Multas
        = raw @tickets
    
      - if @client_history
        %ul.history
          - @client_history.each do |h|
            %li Consultado por #{h.user.insurance.company} el #{h.date.strftime("%d/%m/%Y")}
      - else
        %ul
          %li.none No hay historial.







  #company_report.page{:unactive => "#{@company.nil?}"}  
    - if @company

      .main_block
        .info
          %h2= @company.name
          - if @company.rnc
            %h4 <span>RNC</span> #{@company.rnc.insert(3, '-').insert(7, '-')}
        = link_to 'Imprimir', '#', :class => "print"






      
  #vehicle_report.page{:unactive => "#{@vehicle.nil?}"}  
    - if @vehicle
    
      .main_block
        .info
          %h2= [@vehicle.vehicle_model.vehicle_brand.name, @vehicle.vehicle_model.name, @vehicle.year.to_s].join(' ')
          - if @vehicle.plate
            %h4 <span>Placa</span> #{@vehicle.plate}
          - if @vehicle.vin
            %h4 <span>VIN</span> #{@vehicle.vin}

        = link_to 'Imprimir', '#', :class => "print"
    
    
      .breaker= @vehicle.policies.count.to_s + " pólizas"
      - unless @vehicle.policies.empty?    
        - @vehicle.policies.order("start desc").each do |p|
          .block
            .block_header
              .policy_number= 'Póliza #' + p.policy
              .insurance_name= p.insurance.company
              .coverage_type= get_coverage p.coverage
              .claims_count
                .bubble= p.claims.count.to_s 
                %span  reclamaciones
              .end_date= p.end.strftime("%d/%b/%Y")            
              .start_date= p.start.strftime("%d/%b/%Y")
            .block_subheader= get_client_details(p)
            %table{:cellpading => '0', :cellspacing => 0}
              - unless p.claims.empty?
                %tr
                  %th No. Reclamación
                  %th Vehículo
                  %th Placa
                  %th Chasis
                  %th Fecha
                  %th Tipo
                  %th Estado  
                - p.claims.order("created_at desc").each do |c|
                  %tr{:class => cycle('odd', 'even')}
                    %td= c.number
                    %td= [c.vehicle.vehicle_model.vehicle_brand.name,c.vehicle.vehicle_model.name,c.vehicle.year.to_s].join(' ')
                    %td= c.vehicle.plate
                    %td= c.vehicle.vin
                    %td= c.date.strftime("%d/%b/%Y")
                    %td= c.claim_type.name
                    %td= c.claim_status.status
              - else
                %td.none_found No se encontraron reclamaciones.

#print_footer
  %p *** Fin de página ***
  
#printed_by=  ['Impreso por',current_user.name, current_user.surname, 'de', current_user.insurance.company].join(' ')
        

app/views/searches/new.html.haml
#main_logo

= form_tag searches_path, :id => 'new_search', :method => 'get', :enforce_utf8 => false do
  = text_field_tag :client, '', :placeholder => 'Identificación o RNC', :maxlength => 13, :pattern => ".{9,}", :title => "Mínimo 9 caracteres.", :autofocus => true
  = text_field_tag :vehicle, '', :placeholder => 'Placa o VIN', :maxlength => 17
  = submit_tag "Buscar", :name => nil
  
= render "layouts/footer"

app/views/searches/not_found.html.haml
#Loader
%script{:type => "text/javascript"}
  $("#Loader").fakeLoader({timeToHide:4000, zIndex:"19", spinner:"spinner2", bgColor:"#2C3E50"});
  
#not_found
  = image_tag("icons/not_found.png")
  %br
  %h2{ :style => "color:#fff; margin-top:15px"} La búsqueda no obtuvo resultados
  %br
  = link_to 'Realiza otra búsqueda', root_path, :id => "try_again"